spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: task_user
    password: task_password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
server:
  port: 8080
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: TRACE
    org.hibernate.SQL: DEBUG
